"""Full scene export inside Blender, with contract assertions.

Builds a small scene covering every exported feature, exports it, and checks the resulting
document. The assertions are mostly about the **axis conversion surviving each path** -- entity
transforms, camera, lights, collider poses -- because that is where a Blender host differs from
the Godot one and where a regression would be silent.

Documents land in ``$TMPDIR/paradise_export_test`` so ``tools/run_tests.sh`` can then feed
them to the .NET conformance gate.

Run with::

    blender --background --factory-startup --python tests/integration/test_export_scene.py
"""

from __future__ import annotations

import json
import math
import os
import sys
import tempfile

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, REPO)

import bpy  # noqa: E402

import paradise_blender  # noqa: E402
from paradise_blender.contract import component_ids  # noqa: E402
from paradise_blender.export.scene import export_scene  # noqa: E402


def payload_for(obj, component_id):
    """One component's Data on an exported object, or None.

    An object IS its component list since schema v5, so this takes the list itself — there is no
    entity record to reach through, and no key whose absence means "no such component"."""
    for component in obj:
        if component["Id"] == component_id:
            return component["Data"]
    return None


def name_of(obj) -> str | None:
    """What an object is called, read the only way there is to read it: off its Name component."""
    payload = payload_for(obj, component_ids.NAME)
    return None if payload is None else payload["Value"]


def by_name(document) -> dict:
    return {name_of(o): o for o in document["Entities"] if name_of(o) is not None}


DATA_DIR = os.path.join(tempfile.gettempdir(), "paradise_export_test")

failures: list[str] = []


def check(condition: bool, description: str, detail: str = "") -> None:
    if condition:
        print(f"ok   {description}")
    else:
        print(f"FAIL {description}{(' — ' + detail) if detail else ''}")
        failures.append(description)


def approx(actual, expected, tolerance=1e-4) -> bool:
    if isinstance(expected, (list, tuple)):
        return len(actual) == len(expected) and all(
            abs(a - e) <= tolerance for a, e in zip(actual, expected, strict=True)
        )
    return abs(actual - expected) <= tolerance


def write_authoring_schema() -> None:
    """Put a launcher-style authoring schema in the test's data directory, from the REAL engine.

    The addon no longer vendors a copy of the engine's schema: a game's launcher merges every
    assembly it references into the document it dumps, so the engine's components reach this host
    inside the GAME's schema. That makes a data directory without one a directory in which no
    component can be named — which is the correct behaviour and exactly what this test now has to
    set up, the same way a real project sets it up by building its launcher.

    Generated by asking the bridge to print ``Paradise.Export.AuthoringSchema.Json`` rather than
    by checking a copy in, so this test still exercises the real engine's component definitions.
    The fixture scene authors no components of its own, so the engine's document IS what its
    launcher would dump.
    """
    import subprocess

    bridge = os.path.join(REPO, "tools", "ParadiseBlenderBridge", "ParadiseBlenderBridge.csproj")
    printed = subprocess.run(
        ["dotnet", "run", "--project", bridge, "--", "engine-schema"],
        capture_output=True, text=True, check=True, cwd=REPO).stdout
    os.makedirs(DATA_DIR, exist_ok=True)
    with open(os.path.join(DATA_DIR, "authoring-schema.json"), "w", encoding="utf-8") as file:
        file.write(printed)

    from paradise_blender.contract import authoring as contract_authoring
    contract_authoring._cache.clear()


def _component(component_id: str):
    """One component's schema, as the panel resolves it."""
    from paradise_blender.contract import authoring as contract_authoring

    for component in contract_authoring.schema_for_data_dir(DATA_DIR).components:
        if component.id == component_id:
            return component
    return None


def _point_at(obj, component_id: str, target) -> None:
    """Fill one of a component's host-object references, as the Components panel would.

    ONE store keyed by ``<component-id>/<field>``, which is what replaced the two hand-declared
    collections (``physics_colliders``, ``interactable_colliders``) that made host references an
    engine-component privilege. A test that still reached for those was pointing at properties the
    addon no longer registers.
    """
    from paradise_blender.authoring import authored_components

    component = _component(component_id)
    assert component is not None, f"{component_id} is not in the authoring schema at {DATA_DIR}"
    reference = obj.paradise.host_refs.add()
    reference.key = authored_components.host_ref_key(component)
    reference.target = target


def _attach(obj, component_id: str, **fields) -> None:
    """Attach one authored engine component, as the Components panel would."""
    from paradise_blender.authoring import authored_components

    component = _component(component_id)
    matched = component is not None
    if matched:
        authored_components.enable_component(obj, component)
    # Louder than the silent no-op this used to be: an id the schema does not declare means the
    # transcribed constants and the engine disagree, and every assertion below would then fail
    # for a reason that has nothing to do with what it tests.
    assert matched, f"{component_id} is not in the authoring schema at {DATA_DIR}"
    for field, value in fields.items():
        obj[authored_components.value_key(component_id, field)] = value


def build_scene() -> None:
    # BEFORE anything authors a component: nothing can be named without a schema in the data
    # directory, and the export itself reads it to write each engine payload's CLR type name.
    write_authoring_schema()

    bpy.ops.wm.read_factory_settings(use_empty=True)
    scene = bpy.context.scene
    scene.paradise_project.data_dir = DATA_DIR
    scene.paradise_project.scene_name_override = "export_test"
    scene.paradise_project.export_on_save = False

    # Ground: a wide flat box with a collider, so it becomes walkable navmesh geometry.
    bpy.ops.mesh.primitive_cube_add(size=1.0, location=(0, 0, 0))
    ground = bpy.context.active_object
    ground.name = "Ground"
    ground.scale = (20.0, 20.0, 0.5)
    ground.paradise.is_entity = True

    material = bpy.data.materials.new("mat_ground")
    material.use_nodes = True
    bsdf = material.node_tree.nodes["Principled BSDF"]
    bsdf.inputs["Base Color"].default_value = (0.25, 0.5, 0.75, 1.0)
    bsdf.inputs["Metallic"].default_value = 0.25
    bsdf.inputs["Roughness"].default_value = 0.75
    ground.data.materials.append(material)

    bpy.ops.object.empty_add(type="CUBE", location=(0, 0, 0))
    collider = bpy.context.active_object
    collider.name = "GroundCollider"
    collider.paradise_collider.is_collider = True
    collider.paradise_collider.shape = "Box"
    collider.paradise_collider.layer = 1
    collider.parent = ground
    _point_at(ground, component_ids.COLLIDER, collider)

    # A dynamic prop, placed off-axis so the conversion is observable.
    bpy.ops.mesh.primitive_uv_sphere_add(radius=0.5, location=(1.0, 2.0, 3.0))
    ball = bpy.context.active_object
    ball.name = "Ball"
    ball.paradise.is_entity = True
    _attach(ball, component_ids.RIGIDBODY, BodyType="Dynamic", Mass=2.5)

    bpy.ops.object.empty_add(type="SPHERE", location=(1.0, 2.0, 3.0))
    ball_collider = bpy.context.active_object
    ball_collider.name = "BallCollider"
    ball_collider.paradise_collider.is_collider = True
    ball_collider.paradise_collider.shape = "Sphere"
    ball_collider.parent = ball
    _point_at(ball, component_ids.COLLIDER, ball_collider)

    # An agent, which must be excluded from the navmesh bake.
    bpy.ops.mesh.primitive_cylinder_add(radius=0.4, depth=1.8, location=(-3.0, 0.0, 1.0))
    agent = bpy.context.active_object
    agent.name = "Hero"
    agent.paradise.is_entity = True
    _attach(agent, component_ids.AGENT, MoveSpeed=3.0)

    # Camera at the engine's documented validation pose.
    bpy.ops.object.camera_add(location=(0, -10, 1), rotation=(math.radians(90), 0, 0))
    scene.camera = bpy.context.active_object
    scene.camera.name = "MainCamera"

    bpy.ops.object.light_add(type="SUN", location=(0, 0, 10))
    sun = bpy.context.active_object
    sun.name = "Sun"
    sun.data.energy = 3.0

    bpy.ops.object.light_add(type="SPOT", location=(2, 0, 5))
    spot = bpy.context.active_object
    spot.name = "Spot"
    spot.data.energy = 200.0
    spot.data.spot_size = math.radians(60)

    world = bpy.data.worlds.new("World")
    scene.world = world
    scene.view_settings.view_transform = "AgX"


def main() -> int:
    paradise_blender.register()
    build_scene()

    output = export_scene(bpy.context.scene)
    if output is None or not os.path.exists(output):
        print("FAIL export produced no document")
        return 1

    with open(output, encoding="utf-8") as handle:
        document = json.load(handle)

    print()
    check(document["SchemaVersion"] == 5, "schema version is 5")
    check(all(isinstance(o, list) for o in document["Entities"]),
          "every object is a bare component array, with no record around it")

    objects = by_name(document)
    # The environment is an object too, and it is the one object with no name: nothing in the
    # .blend corresponds to it, so there is nothing to name it after.
    check(set(objects) == {"Ball", "Ground", "Hero", "Sun", "Spot"},
          "the three entities and the two lamps are objects", str(sorted(objects)))
    unnamed = [o for o in document["Entities"] if name_of(o) is None]
    check(len(unnamed) == 1 and payload_for(unnamed[0], component_ids.ENVIRONMENT) is not None,
          "the scene's environment is one unnamed object carrying the Environment component")

    # -- axis conversion --------------------------------------------------------------
    ball = objects["Ball"]
    world = payload_for(ball, component_ids.TRANSFORM)["World"]
    check(approx(world[12:15], [1.0, 3.0, -2.0]),
          "Blender (1, 2, 3) converts to contract (1, 3, -2), at flat indices 12/13/14",
          str(world[12:15]))

    ground = objects["Ground"]
    # The scale is read back OUT of the matrix rather than off a decomposed field, because the
    # decomposed fields are gone: one placement, stated once. Column-major, so the first column's
    # length is the X scale and the second's is Y.
    ground_world = payload_for(ground, component_ids.TRANSFORM)["World"]
    scales = [
        math.sqrt(sum(ground_world[column * 4 + row] ** 2 for row in range(3)))
        for column in range(3)
    ]
    check(approx(scales, [20.0, 0.5, 20.0]),
          "Blender scale (20, 20, 0.5) converts to contract (20, 0.5, 20)", str(scales))

    # -- components -------------------------------------------------------------------
    check(payload_for(ball, component_ids.RIGIDBODY)["BodyType"] == "Dynamic",
          "the dynamic prop exports BodyType Dynamic")
    check(approx(payload_for(ball, component_ids.RIGIDBODY)["Mass"], 2.5),
          "dynamic body mass carries through")
    check(payload_for(ground, component_ids.RIGIDBODY)["BodyType"] == "Static",
          "an ordinary collidable entity exports BodyType Static")
    check(approx(payload_for(ground, component_ids.RIGIDBODY)["Mass"], 0.0),
          "a static body exports zero mass")

    hero = objects["Hero"]
    check(payload_for(hero, component_ids.AGENT) is not None, "the agent exports an Agent component")
    check(approx(payload_for(hero, component_ids.AGENT)["MoveSpeed"], 3.0),
          "agent move speed carries through")
    check(payload_for(hero, component_ids.AGENT)["IdleClip"] == "Idle",
          "an unset idle clip falls back to the shared default")

    shapes = payload_for(ground, component_ids.COLLIDER)["Colliders"]
    check(len(shapes) == 1 and shapes[0]["ShapeType"] == "Box", "the box collider exported")
    check(shapes[0]["Layer"] == 1, "the collider's layer index carries through")
    check(all(s > 0 for s in shapes[0]["Size"]),
          "the collider derived a non-zero size from an empty's display bounds", str(shapes[0]["Size"]))

    sphere_shape = payload_for(ball, component_ids.COLLIDER)["Colliders"][0]
    check(sphere_shape["ShapeType"] == "Sphere" and sphere_shape["Radius"] > 0,
          "the sphere collider exported with a radius")

    # NO RENDERABLE, and that is the assertion. "This object draws" used to be inferred from the
    # object having mesh data; it is a component an author attaches now, pointing at the object
    # whose geometry to export. A scene that authors none exports none.
    check(payload_for(ground, component_ids.RENDERABLE) is None,
          "the exporter no longer derives a Renderable from an object having geometry")

    # The SLOTS are still derived, and the asymmetry is deliberate: which GLB an object draws is a
    # decision, and which materials override its primitives is Blender's material stack.
    materials = payload_for(ground, component_ids.MATERIALS)
    check(materials is not None and materials["Slots"] == ["materials/mat_ground.json"],
          "the material slot is derived and references its contract field", str(materials))

    # -- lighting and environment -----------------------------------------------------
    # A lamp is an OBJECT carrying a Light, not an entry in a document-level lighting state. It
    # used to be both, depending on whether the author had marked it as an entity, with a rule
    # saying it must not be both at once or the runtime would light it twice.
    lights = {
        name: payload_for(objects[name], component_ids.LIGHT) for name in ("Sun", "Spot")
    }
    check(all(light is not None for light in lights.values()),
          "both lamps exported as objects carrying a Light", str(sorted(objects)))
    check(lights["Sun"]["Type"] == "Directional", "a sun lamp exports as Directional")
    check(approx(lights["Sun"]["Direction"], [0.0, -1.0, 0.0]),
          "an unrotated sun points down in contract axes", str(lights["Sun"]["Direction"]))
    check(approx(lights["Sun"]["Intensity"], 3.0 / math.pi),
          "sun W/m^2 divides by pi to match Godot's pi-folded energy convention",
          str(lights["Sun"]["Intensity"]))
    check(lights["Spot"]["Type"] == "Spot", "a spot lamp exports as Spot")
    check(approx(lights["Spot"]["SpotAngle"], 60.0),
          "Blender's spot_size is already the full cone angle and is not doubled",
          str(lights["Spot"]["SpotAngle"]))
    check(approx(lights["Spot"]["Intensity"], 2.0),
          "200 W maps to intensity 2 via the documented calibration",
          str(lights["Spot"]["Intensity"]))

    environment = payload_for(unnamed[0], component_ids.ENVIRONMENT)
    check(environment["TonemapMode"] == "Agx", "the AgX view transform maps to the Agx operator")
    # The two shadow settings moved onto the environment with it; they sat on the lighting block
    # for want of anywhere else, and they are as much "how this scene is lit" as the ambient is.
    check("ShadowMapSize" in environment and "ShadowBlur" in environment,
          "the shadow settings travel on the environment component", str(sorted(environment))[:80])

    # -- navmesh ----------------------------------------------------------------------
    # The walkable-geometry filter must exclude DYNAMIC bodies: the ball is collidable but
    # moves, and baking it would freeze a bump into the walkable surface at its spawn (the
    # Godot host bakes StaticColliders only — same semantics). Ball world position converted
    # to contract axes is (1, 3, -2); nothing in the collected geometry may be near it.
    from paradise_blender.export.navmesh import collect_walkable_geometry

    nav_vertices, nav_triangles = collect_walkable_geometry(bpy.context.scene, DATA_DIR)
    check(len(nav_triangles) > 0, "static collidable geometry reaches the navmesh bake")
    ball_near = any(
        abs(nav_vertices[i] - 1.0) < 0.6
        and abs(nav_vertices[i + 1] - 3.0) < 0.6
        and abs(nav_vertices[i + 2] - -2.0) < 0.6
        for i in range(0, len(nav_vertices), 3)
    )
    check(not ball_near, "the dynamic ball is excluded from the walkable geometry")

    # The document no longer names the navmesh: the NavMeshFile key went with the rest of the
    # document shell, and it stated what the filename already says — the bake writes
    # <scene>.navmesh.bin beside <scene>.json.
    navmesh = os.path.join(DATA_DIR, "scenes", "export_test.navmesh.bin")
    if os.path.exists(navmesh):
        check(os.path.getsize(navmesh) > 0,
              "the navmesh binary was baked and is non-empty")

        # -- bake button + viewport preview -------------------------------------------
        from paradise_blender.export.navmesh_preview import find_preview_object

        result = bpy.ops.paradise.bake_navmesh()
        check(result == {"FINISHED"}, "the bake operator finishes when the bridge is available")

        preview = find_preview_object()
        check(preview is not None, "the bake operator builds a preview object")
        if preview is not None:
            check(len(preview.data.polygons) > 0, "the preview mesh has faces")
            check(preview.hide_select and preview.hide_render,
                  "the preview is unselectable and never renders")
            check(not getattr(preview.paradise, "is_entity", False),
                  "the preview is not an entity, so re-exports ignore it")
            check(bpy.context.scene.paradise_project.navmesh_preview,
                  "baking turns the preview toggle on")
            check(not preview.hide_viewport, "a fresh bake is visible")

            # The walkable surface must sit ON the ground in Blender axes (top of the ground
            # box is z=0.25 here) — a wrong inverse conversion would tip the mesh sideways.
            zs = [v.co.z for v in preview.data.vertices]
            spans = (max(zs) - min(zs)) if zs else 1e9
            check(spans < 1.0, "the preview lies flat in Blender's Z-up axes", f"z span {spans:.2f}")

            bpy.context.scene.paradise_project.navmesh_preview = False
            check(preview.hide_viewport, "turning the toggle off hides the preview")

        # -- per-scene bake settings ---------------------------------------------------
        from paradise_blender.export.navmesh import BAKE_SETTINGS, bake_settings

        # Key-wise with tolerance: the properties are float32, so 0.1 does not round-trip
        # to exactly 0.1.
        resolved = bake_settings(bpy.context.scene)
        check(set(resolved) == set(BAKE_SETTINGS)
              and all(approx(resolved[key], BAKE_SETTINGS[key]) for key in BAKE_SETTINGS),
              "an untouched scene bakes with the engine-default settings", str(resolved))

        with open(navmesh, "rb") as handle:
            default_bake = handle.read()

        # A fatter agent erodes more walkable area, so the binary must change — this proves
        # the panel settings actually reach Recast rather than dying in the JSON handoff.
        bpy.context.scene.paradise_project.navmesh_agent_radius = 0.9
        check(approx(bake_settings(bpy.context.scene)["agentRadius"], 0.9),
              "the scene property feeds the bake settings")
        result = bpy.ops.paradise.bake_navmesh()
        check(result == {"FINISHED"}, "re-baking with custom settings finishes")
        with open(navmesh, "rb") as handle:
            fat_bake = handle.read()
        check(fat_bake != default_bake,
              "a different agent radius produces a different navmesh binary")
        bpy.context.scene.paradise_project.navmesh_agent_radius = 0.4
    else:
        print("     (navmesh skipped — the .NET bridge was unavailable)")

    # -- data-directory cleanup, and the gate in front of it --------------------------
    # The only step of an export that DELETES. `build_scene` never touches `prune_data`, so
    # this exercises the shipped default -- an addon update must not start removing an
    # author's files on the next save, which with `export_on_save` on is one keystroke away.
    orphan = os.path.join(DATA_DIR, "Models", "NoLongerReferenced.glb")
    os.makedirs(os.path.dirname(orphan), exist_ok=True)

    def plant() -> None:
        with open(orphan, "wb") as handle:
            handle.write(b"glTF\x02\x00\x00\x00")  # unreferenced, and not a valid GLB

    plant()
    check(not bpy.context.scene.paradise_project.prune_data,
          "the data-directory cleanup is off unless a project opts in")
    export_scene(bpy.context.scene)
    check(os.path.exists(orphan),
          "an export with the cleanup off deletes nothing, even an unreferenced file")

    bpy.context.scene.paradise_project.prune_data = True
    export_scene(bpy.context.scene)
    check(not os.path.exists(orphan), "opting in removes the unreferenced file")

    # Owned-directory and derived-artifact rules, against a live export rather than a fixture.
    plant()
    keep_audio = os.path.join(DATA_DIR, "audio", "Bank.bnk")
    keep_note = os.path.join(DATA_DIR, "Models", "notes.txt")
    keep_primitive = os.path.join(DATA_DIR, "primitives", "Cube.glb")
    keep_sheet = os.path.join(DATA_DIR, "sprites", "Fire.png")
    keep_sidecar = os.path.join(DATA_DIR, "sprites", "Fire.ktx2")
    for path in (keep_audio, keep_note, keep_primitive, keep_sheet, keep_sidecar):
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "wb") as handle:
            handle.write(b"payload")

    export_scene(bpy.context.scene)
    check(not os.path.exists(orphan), "the cleanup still collects a genuine orphan")
    check(os.path.exists(keep_audio), "Wwise banks are outside the owned directories")
    check(os.path.exists(keep_note), "an unowned extension inside an owned directory survives")
    check(os.path.exists(keep_primitive),
          "generated primitives are the Godot host's, and this exporter never writes one")
    check(os.path.exists(keep_sidecar),
          "a KTX2 whose source image is still there is a transcode target, not an orphan")
    bpy.context.scene.paradise_project.prune_data = False

    # -- side artifacts ---------------------------------------------------------------
    check(os.path.exists(os.path.join(DATA_DIR, "ProjectSettings.json")),
          "ProjectSettings.json was written")
    check(os.path.exists(os.path.join(DATA_DIR, "materials", "mat_ground.json")),
          "the material document was written")

    print()
    if failures:
        print(f"{len(failures)} check(s) FAILED:")
        for failure in failures:
            print(f"  - {failure}")
        return 1

    print(f"All checks passed. Documents in {DATA_DIR}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
